create database order_tracking_system;

use order_tracking_system;

#Customer: cid, cname, phoneNo, address, totalOrders

create table customer(
cid int primary key auto_increment,
cname varchar(100),
phonoNo bigint not null,
address varchar(150) not null,
totalorders int default(0));

describe customer;

insert into customer values (1,"Yash Shinde",9876543210,"Kolki-Phaltan",0);

select * from customer;

#Supplier: sid, sname, address, email, phoneNo

create table supplier(
sid int primary key auto_increment,
sname varchar(100),
address varchar(100) not null,
email varchar(50) not null,
phonoNo bigint);

insert into  supplier value(1,"Pratik Shinde","Phaltan","shinde7388pratik@gmail.com",7057069812);

#Product: pid, pname, price,sid

create table product(
pid int primary key auto_increment,
pname varchar(50) not null,
price int default(0),
sid int not null,
foreign key (sid) references supplier(sid));

insert into product value (1,"BOAT-Smart Watch",2500,1);

#OrderDetails:  orderid(autogenerated), cid, pid, dateOfOrder, statusOfOrder, deliveredDate
     #Note: If the order id not delivered then deliveredDate will be null
     
create table orderdetails (
orderid int primary key auto_increment,
cid int,
pid int,
foreign key(cid) references customer(cid),
foreign key(pid)references product(pid),
dateOfOrder date default(curdate()),
Status varchar(100),
deliveredDate date default(null));

insert into orderdetails value(3,2,1,"2024-03-03","Placed","2024-03-06");


alter table orderdetails
modify Status varchar(50) default('Shipped');
